// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BackendRedispatch backend redispatch
// swagger:model backendRedispatch
type BackendRedispatch struct {

	// enabled
	// Required: true
	// Enum: [enabled disabled]
	Enabled *string `json:"enabled"`

	// interval
	Interval int64 `json:"interval,omitempty"`
}

// Validate validates this backend redispatch
func (m *BackendRedispatch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var backendRedispatchTypeEnabledPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled","disabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		backendRedispatchTypeEnabledPropEnum = append(backendRedispatchTypeEnabledPropEnum, v)
	}
}

const (

	// BackendRedispatchEnabledEnabled captures enum value "enabled"
	BackendRedispatchEnabledEnabled string = "enabled"

	// BackendRedispatchEnabledDisabled captures enum value "disabled"
	BackendRedispatchEnabledDisabled string = "disabled"
)

// prop value enum
func (m *BackendRedispatch) validateEnabledEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, backendRedispatchTypeEnabledPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *BackendRedispatch) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	// value enum
	if err := m.validateEnabledEnum("enabled", "body", *m.Enabled); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BackendRedispatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackendRedispatch) UnmarshalBinary(b []byte) error {
	var res BackendRedispatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
