// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BackendHttpchk backend httpchk
// swagger:model backendHttpchk
type BackendHttpchk struct {

	// method
	// Enum: [HEAD PUT POST GET TRACE PATCH]
	Method string `json:"method,omitempty"`

	// uri
	// Pattern: ^[^\s]+$
	URI string `json:"uri,omitempty"`

	// version
	// Pattern: ^[^\s]+$
	Version string `json:"version,omitempty"`
}

// Validate validates this backend httpchk
func (m *BackendHttpchk) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURI(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var backendHttpchkTypeMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["HEAD","PUT","POST","GET","TRACE","PATCH"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		backendHttpchkTypeMethodPropEnum = append(backendHttpchkTypeMethodPropEnum, v)
	}
}

const (

	// BackendHttpchkMethodHEAD captures enum value "HEAD"
	BackendHttpchkMethodHEAD string = "HEAD"

	// BackendHttpchkMethodPUT captures enum value "PUT"
	BackendHttpchkMethodPUT string = "PUT"

	// BackendHttpchkMethodPOST captures enum value "POST"
	BackendHttpchkMethodPOST string = "POST"

	// BackendHttpchkMethodGET captures enum value "GET"
	BackendHttpchkMethodGET string = "GET"

	// BackendHttpchkMethodTRACE captures enum value "TRACE"
	BackendHttpchkMethodTRACE string = "TRACE"

	// BackendHttpchkMethodPATCH captures enum value "PATCH"
	BackendHttpchkMethodPATCH string = "PATCH"
)

// prop value enum
func (m *BackendHttpchk) validateMethodEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, backendHttpchkTypeMethodPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *BackendHttpchk) validateMethod(formats strfmt.Registry) error {

	if swag.IsZero(m.Method) { // not required
		return nil
	}

	// value enum
	if err := m.validateMethodEnum("method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

func (m *BackendHttpchk) validateURI(formats strfmt.Registry) error {

	if swag.IsZero(m.URI) { // not required
		return nil
	}

	if err := validate.Pattern("uri", "body", string(m.URI), `^[^\s]+$`); err != nil {
		return err
	}

	return nil
}

func (m *BackendHttpchk) validateVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.Version) { // not required
		return nil
	}

	if err := validate.Pattern("version", "body", string(m.Version), `^[^\s]+$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BackendHttpchk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackendHttpchk) UnmarshalBinary(b []byte) error {
	var res BackendHttpchk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
