// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Frontend Frontend
//
// HAProxy frontend configuration
// swagger:model frontend
type Frontend struct {

	// client inactivity timeout
	ClientInactivityTimeout *int64 `json:"client_inactivity_timeout,omitempty"`

	// client tcp keep alive
	// Enum: [disabled enabled]
	ClientTCPKeepAlive string `json:"client_tcp_keep_alive,omitempty"`

	// continuous statistics
	// Enum: [enabled]
	ContinuousStatistics string `json:"continuous_statistics,omitempty"`

	// default farm
	DefaultFarm string `json:"default_farm,omitempty"`

	// http connection mode
	// Enum: [tunnel passive-close forced-close server-close keep-alive pretend-keepalive]
	HTTPConnectionMode string `json:"http_connection_mode,omitempty"`

	// http keepalive timeout
	HTTPKeepaliveTimeout *int64 `json:"http_keepalive_timeout,omitempty"`

	// http request timeout
	HTTPRequestTimeout *int64 `json:"http_request_timeout,omitempty"`

	// http xff header insert
	// Enum: [enabled]
	HTTPXffHeaderInsert string `json:"http_xff_header_insert,omitempty"`

	// http xff header insert except
	HTTPXffHeaderInsertExcept string `json:"http_xff_header_insert_except,omitempty"`

	// http xff header insert ifnone
	// Enum: [enabled]
	HTTPXffHeaderInsertIfnone string `json:"http_xff_header_insert_ifnone,omitempty"`

	// http xff header insert name
	HTTPXffHeaderInsertName string `json:"http_xff_header_insert_name,omitempty"`

	// log
	// Enum: [enabled]
	Log string `json:"log,omitempty"`

	// log format
	// Enum: [tcp http clf custom]
	LogFormat string `json:"log_format,omitempty"`

	// log format custom
	LogFormatCustom string `json:"log_format_custom,omitempty"`

	// log format sd
	LogFormatSd string `json:"log_format_sd,omitempty"`

	// log ignore null
	// Enum: [enabled disabled]
	LogIgnoreNull string `json:"log_ignore_null,omitempty"`

	// log separate errors
	// Enum: [enabled disabled]
	LogSeparateErrors string `json:"log_separate_errors,omitempty"`

	// log tag
	LogTag string `json:"log_tag,omitempty"`

	// max connections
	MaxConnections *int64 `json:"max_connections,omitempty"`

	// name
	// Required: true
	Name string `json:"name"`

	// protocol
	// Enum: [http tcp]
	Protocol string `json:"protocol,omitempty"`

	// tcp smart accept
	// Enum: [disabled enabled]
	TCPSmartAccept string `json:"tcp_smart_accept,omitempty"`

	// tcpreq inspect delay
	TcpreqInspectDelay *int64 `json:"tcpreq_inspect_delay,omitempty"`
}

// Validate validates this frontend
func (m *Frontend) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientTCPKeepAlive(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContinuousStatistics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHTTPConnectionMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHTTPXffHeaderInsert(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHTTPXffHeaderInsertIfnone(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogIgnoreNull(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogSeparateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTCPSmartAccept(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var frontendTypeClientTCPKeepAlivePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["disabled","enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeClientTCPKeepAlivePropEnum = append(frontendTypeClientTCPKeepAlivePropEnum, v)
	}
}

const (

	// FrontendClientTCPKeepAliveDisabled captures enum value "disabled"
	FrontendClientTCPKeepAliveDisabled string = "disabled"

	// FrontendClientTCPKeepAliveEnabled captures enum value "enabled"
	FrontendClientTCPKeepAliveEnabled string = "enabled"
)

// prop value enum
func (m *Frontend) validateClientTCPKeepAliveEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeClientTCPKeepAlivePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateClientTCPKeepAlive(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientTCPKeepAlive) { // not required
		return nil
	}

	// value enum
	if err := m.validateClientTCPKeepAliveEnum("client_tcp_keep_alive", "body", m.ClientTCPKeepAlive); err != nil {
		return err
	}

	return nil
}

var frontendTypeContinuousStatisticsPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeContinuousStatisticsPropEnum = append(frontendTypeContinuousStatisticsPropEnum, v)
	}
}

const (

	// FrontendContinuousStatisticsEnabled captures enum value "enabled"
	FrontendContinuousStatisticsEnabled string = "enabled"
)

// prop value enum
func (m *Frontend) validateContinuousStatisticsEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeContinuousStatisticsPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateContinuousStatistics(formats strfmt.Registry) error {

	if swag.IsZero(m.ContinuousStatistics) { // not required
		return nil
	}

	// value enum
	if err := m.validateContinuousStatisticsEnum("continuous_statistics", "body", m.ContinuousStatistics); err != nil {
		return err
	}

	return nil
}

var frontendTypeHTTPConnectionModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["tunnel","passive-close","forced-close","server-close","keep-alive","pretend-keepalive"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeHTTPConnectionModePropEnum = append(frontendTypeHTTPConnectionModePropEnum, v)
	}
}

const (

	// FrontendHTTPConnectionModeTunnel captures enum value "tunnel"
	FrontendHTTPConnectionModeTunnel string = "tunnel"

	// FrontendHTTPConnectionModePassiveClose captures enum value "passive-close"
	FrontendHTTPConnectionModePassiveClose string = "passive-close"

	// FrontendHTTPConnectionModeForcedClose captures enum value "forced-close"
	FrontendHTTPConnectionModeForcedClose string = "forced-close"

	// FrontendHTTPConnectionModeServerClose captures enum value "server-close"
	FrontendHTTPConnectionModeServerClose string = "server-close"

	// FrontendHTTPConnectionModeKeepAlive captures enum value "keep-alive"
	FrontendHTTPConnectionModeKeepAlive string = "keep-alive"

	// FrontendHTTPConnectionModePretendKeepalive captures enum value "pretend-keepalive"
	FrontendHTTPConnectionModePretendKeepalive string = "pretend-keepalive"
)

// prop value enum
func (m *Frontend) validateHTTPConnectionModeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeHTTPConnectionModePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateHTTPConnectionMode(formats strfmt.Registry) error {

	if swag.IsZero(m.HTTPConnectionMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateHTTPConnectionModeEnum("http_connection_mode", "body", m.HTTPConnectionMode); err != nil {
		return err
	}

	return nil
}

var frontendTypeHTTPXffHeaderInsertPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeHTTPXffHeaderInsertPropEnum = append(frontendTypeHTTPXffHeaderInsertPropEnum, v)
	}
}

const (

	// FrontendHTTPXffHeaderInsertEnabled captures enum value "enabled"
	FrontendHTTPXffHeaderInsertEnabled string = "enabled"
)

// prop value enum
func (m *Frontend) validateHTTPXffHeaderInsertEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeHTTPXffHeaderInsertPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateHTTPXffHeaderInsert(formats strfmt.Registry) error {

	if swag.IsZero(m.HTTPXffHeaderInsert) { // not required
		return nil
	}

	// value enum
	if err := m.validateHTTPXffHeaderInsertEnum("http_xff_header_insert", "body", m.HTTPXffHeaderInsert); err != nil {
		return err
	}

	return nil
}

var frontendTypeHTTPXffHeaderInsertIfnonePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeHTTPXffHeaderInsertIfnonePropEnum = append(frontendTypeHTTPXffHeaderInsertIfnonePropEnum, v)
	}
}

const (

	// FrontendHTTPXffHeaderInsertIfnoneEnabled captures enum value "enabled"
	FrontendHTTPXffHeaderInsertIfnoneEnabled string = "enabled"
)

// prop value enum
func (m *Frontend) validateHTTPXffHeaderInsertIfnoneEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeHTTPXffHeaderInsertIfnonePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateHTTPXffHeaderInsertIfnone(formats strfmt.Registry) error {

	if swag.IsZero(m.HTTPXffHeaderInsertIfnone) { // not required
		return nil
	}

	// value enum
	if err := m.validateHTTPXffHeaderInsertIfnoneEnum("http_xff_header_insert_ifnone", "body", m.HTTPXffHeaderInsertIfnone); err != nil {
		return err
	}

	return nil
}

var frontendTypeLogPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeLogPropEnum = append(frontendTypeLogPropEnum, v)
	}
}

const (

	// FrontendLogEnabled captures enum value "enabled"
	FrontendLogEnabled string = "enabled"
)

// prop value enum
func (m *Frontend) validateLogEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeLogPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateLog(formats strfmt.Registry) error {

	if swag.IsZero(m.Log) { // not required
		return nil
	}

	// value enum
	if err := m.validateLogEnum("log", "body", m.Log); err != nil {
		return err
	}

	return nil
}

var frontendTypeLogFormatPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["tcp","http","clf","custom"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeLogFormatPropEnum = append(frontendTypeLogFormatPropEnum, v)
	}
}

const (

	// FrontendLogFormatTCP captures enum value "tcp"
	FrontendLogFormatTCP string = "tcp"

	// FrontendLogFormatHTTP captures enum value "http"
	FrontendLogFormatHTTP string = "http"

	// FrontendLogFormatClf captures enum value "clf"
	FrontendLogFormatClf string = "clf"

	// FrontendLogFormatCustom captures enum value "custom"
	FrontendLogFormatCustom string = "custom"
)

// prop value enum
func (m *Frontend) validateLogFormatEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeLogFormatPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateLogFormat(formats strfmt.Registry) error {

	if swag.IsZero(m.LogFormat) { // not required
		return nil
	}

	// value enum
	if err := m.validateLogFormatEnum("log_format", "body", m.LogFormat); err != nil {
		return err
	}

	return nil
}

var frontendTypeLogIgnoreNullPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled","disabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeLogIgnoreNullPropEnum = append(frontendTypeLogIgnoreNullPropEnum, v)
	}
}

const (

	// FrontendLogIgnoreNullEnabled captures enum value "enabled"
	FrontendLogIgnoreNullEnabled string = "enabled"

	// FrontendLogIgnoreNullDisabled captures enum value "disabled"
	FrontendLogIgnoreNullDisabled string = "disabled"
)

// prop value enum
func (m *Frontend) validateLogIgnoreNullEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeLogIgnoreNullPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateLogIgnoreNull(formats strfmt.Registry) error {

	if swag.IsZero(m.LogIgnoreNull) { // not required
		return nil
	}

	// value enum
	if err := m.validateLogIgnoreNullEnum("log_ignore_null", "body", m.LogIgnoreNull); err != nil {
		return err
	}

	return nil
}

var frontendTypeLogSeparateErrorsPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled","disabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeLogSeparateErrorsPropEnum = append(frontendTypeLogSeparateErrorsPropEnum, v)
	}
}

const (

	// FrontendLogSeparateErrorsEnabled captures enum value "enabled"
	FrontendLogSeparateErrorsEnabled string = "enabled"

	// FrontendLogSeparateErrorsDisabled captures enum value "disabled"
	FrontendLogSeparateErrorsDisabled string = "disabled"
)

// prop value enum
func (m *Frontend) validateLogSeparateErrorsEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeLogSeparateErrorsPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateLogSeparateErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.LogSeparateErrors) { // not required
		return nil
	}

	// value enum
	if err := m.validateLogSeparateErrorsEnum("log_separate_errors", "body", m.LogSeparateErrors); err != nil {
		return err
	}

	return nil
}

func (m *Frontend) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

var frontendTypeProtocolPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["http","tcp"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeProtocolPropEnum = append(frontendTypeProtocolPropEnum, v)
	}
}

const (

	// FrontendProtocolHTTP captures enum value "http"
	FrontendProtocolHTTP string = "http"

	// FrontendProtocolTCP captures enum value "tcp"
	FrontendProtocolTCP string = "tcp"
)

// prop value enum
func (m *Frontend) validateProtocolEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeProtocolPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateProtocol(formats strfmt.Registry) error {

	if swag.IsZero(m.Protocol) { // not required
		return nil
	}

	// value enum
	if err := m.validateProtocolEnum("protocol", "body", m.Protocol); err != nil {
		return err
	}

	return nil
}

var frontendTypeTCPSmartAcceptPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["disabled","enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontendTypeTCPSmartAcceptPropEnum = append(frontendTypeTCPSmartAcceptPropEnum, v)
	}
}

const (

	// FrontendTCPSmartAcceptDisabled captures enum value "disabled"
	FrontendTCPSmartAcceptDisabled string = "disabled"

	// FrontendTCPSmartAcceptEnabled captures enum value "enabled"
	FrontendTCPSmartAcceptEnabled string = "enabled"
)

// prop value enum
func (m *Frontend) validateTCPSmartAcceptEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, frontendTypeTCPSmartAcceptPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Frontend) validateTCPSmartAccept(formats strfmt.Registry) error {

	if swag.IsZero(m.TCPSmartAccept) { // not required
		return nil
	}

	// value enum
	if err := m.validateTCPSmartAcceptEnum("tcp_smart_accept", "body", m.TCPSmartAccept); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Frontend) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Frontend) UnmarshalBinary(b []byte) error {
	var res Frontend
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
