// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetHAProxyConfigurationOKBody get h a proxy configuration o k body
// swagger:model getHAProxyConfigurationOKBody
type GetHAProxyConfigurationOKBody struct {

	// version
	Version int64 `json:"_version,omitempty"`

	// data
	Data string `json:"data,omitempty"`
}

// Validate validates this get h a proxy configuration o k body
func (m *GetHAProxyConfigurationOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetHAProxyConfigurationOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetHAProxyConfigurationOKBody) UnmarshalBinary(b []byte) error {
	var res GetHAProxyConfigurationOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
