// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProcessInfo HAProxy Information
//
// General HAProxy process information
// swagger:model process_info
type ProcessInfo struct {

	// haproxy
	Haproxy *ProcessInfoHaproxy `json:"haproxy,omitempty"`
}

// Validate validates this process info
func (m *ProcessInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHaproxy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessInfo) validateHaproxy(formats strfmt.Registry) error {

	if swag.IsZero(m.Haproxy) { // not required
		return nil
	}

	if m.Haproxy != nil {
		if err := m.Haproxy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("haproxy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProcessInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessInfo) UnmarshalBinary(b []byte) error {
	var res ProcessInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
