// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProcessInfoHaproxy process info haproxy
// swagger:model processInfoHaproxy
type ProcessInfoHaproxy struct {

	// The address of the replying server
	Address string `json:"address,omitempty"`

	// Process id of the replying worker process
	Pid *int64 `json:"pid,omitempty"`

	// Process id of the master process
	Ppid *int64 `json:"ppid,omitempty"`

	// Number of spawned processes
	Processes *int64 `json:"processes,omitempty"`

	// Current time in milliseconds since Epoch.
	// Format: date-time
	Time strfmt.DateTime `json:"time,omitempty"`

	// HAProxy version string
	Version string `json:"version,omitempty"`
}

// Validate validates this process info haproxy
func (m *ProcessInfoHaproxy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessInfoHaproxy) validateTime(formats strfmt.Registry) error {

	if swag.IsZero(m.Time) { // not required
		return nil
	}

	if err := validate.FormatOf("time", "body", "date-time", m.Time.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProcessInfoHaproxy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessInfoHaproxy) UnmarshalBinary(b []byte) error {
	var res ProcessInfoHaproxy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
