// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SiteFarmsItemsBalance site farms items balance
// swagger:model siteFarmsItemsBalance
type SiteFarmsItemsBalance struct {

	// algorithm
	// Enum: [roundrobin static-rr leastconn first source uri url_param random]
	Algorithm string `json:"algorithm,omitempty"`

	// arguments
	Arguments []string `json:"arguments"`
}

// Validate validates this site farms items balance
func (m *SiteFarmsItemsBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateArguments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var siteFarmsItemsBalanceTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["roundrobin","static-rr","leastconn","first","source","uri","url_param","random"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		siteFarmsItemsBalanceTypeAlgorithmPropEnum = append(siteFarmsItemsBalanceTypeAlgorithmPropEnum, v)
	}
}

const (

	// SiteFarmsItemsBalanceAlgorithmRoundrobin captures enum value "roundrobin"
	SiteFarmsItemsBalanceAlgorithmRoundrobin string = "roundrobin"

	// SiteFarmsItemsBalanceAlgorithmStaticRr captures enum value "static-rr"
	SiteFarmsItemsBalanceAlgorithmStaticRr string = "static-rr"

	// SiteFarmsItemsBalanceAlgorithmLeastconn captures enum value "leastconn"
	SiteFarmsItemsBalanceAlgorithmLeastconn string = "leastconn"

	// SiteFarmsItemsBalanceAlgorithmFirst captures enum value "first"
	SiteFarmsItemsBalanceAlgorithmFirst string = "first"

	// SiteFarmsItemsBalanceAlgorithmSource captures enum value "source"
	SiteFarmsItemsBalanceAlgorithmSource string = "source"

	// SiteFarmsItemsBalanceAlgorithmURI captures enum value "uri"
	SiteFarmsItemsBalanceAlgorithmURI string = "uri"

	// SiteFarmsItemsBalanceAlgorithmURLParam captures enum value "url_param"
	SiteFarmsItemsBalanceAlgorithmURLParam string = "url_param"

	// SiteFarmsItemsBalanceAlgorithmRandom captures enum value "random"
	SiteFarmsItemsBalanceAlgorithmRandom string = "random"
)

// prop value enum
func (m *SiteFarmsItemsBalance) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, siteFarmsItemsBalanceTypeAlgorithmPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SiteFarmsItemsBalance) validateAlgorithm(formats strfmt.Registry) error {

	if swag.IsZero(m.Algorithm) { // not required
		return nil
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *SiteFarmsItemsBalance) validateArguments(formats strfmt.Registry) error {

	if swag.IsZero(m.Arguments) { // not required
		return nil
	}

	for i := 0; i < len(m.Arguments); i++ {

		if err := validate.Pattern("arguments"+"."+strconv.Itoa(i), "body", string(m.Arguments[i]), `^[^\s]+$`); err != nil {
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SiteFarmsItemsBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SiteFarmsItemsBalance) UnmarshalBinary(b []byte) error {
	var res SiteFarmsItemsBalance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
