// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StickResponseRule Stick Response Rule
//
// Define a response pattern matching condition to create an entry in a stickiness table.
// swagger:model stick_response_rule
type StickResponseRule struct {

	// cond
	// Enum: [if unless]
	Cond string `json:"cond,omitempty"`

	// cond test
	CondTest string `json:"cond_test,omitempty"`

	// id
	// Required: true
	ID int64 `json:"id"`

	// pattern
	Pattern string `json:"pattern,omitempty"`

	// table
	Table string `json:"table,omitempty"`

	// type
	// Required: true
	// Enum: [storeonly]
	Type string `json:"type"`
}

// Validate validates this stick response rule
func (m *StickResponseRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCond(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var stickResponseRuleTypeCondPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["if","unless"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		stickResponseRuleTypeCondPropEnum = append(stickResponseRuleTypeCondPropEnum, v)
	}
}

const (

	// StickResponseRuleCondIf captures enum value "if"
	StickResponseRuleCondIf string = "if"

	// StickResponseRuleCondUnless captures enum value "unless"
	StickResponseRuleCondUnless string = "unless"
)

// prop value enum
func (m *StickResponseRule) validateCondEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, stickResponseRuleTypeCondPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *StickResponseRule) validateCond(formats strfmt.Registry) error {

	if swag.IsZero(m.Cond) { // not required
		return nil
	}

	// value enum
	if err := m.validateCondEnum("cond", "body", m.Cond); err != nil {
		return err
	}

	return nil
}

func (m *StickResponseRule) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

var stickResponseRuleTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["storeonly"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		stickResponseRuleTypeTypePropEnum = append(stickResponseRuleTypeTypePropEnum, v)
	}
}

const (

	// StickResponseRuleTypeStoreonly captures enum value "storeonly"
	StickResponseRuleTypeStoreonly string = "storeonly"
)

// prop value enum
func (m *StickResponseRule) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, stickResponseRuleTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *StickResponseRule) validateType(formats strfmt.Registry) error {

	if err := validate.RequiredString("type", "body", string(m.Type)); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StickResponseRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StickResponseRule) UnmarshalBinary(b []byte) error {
	var res StickResponseRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
