// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransactionOperationsItems transaction operations items
// swagger:model transactionOperationsItems
type TransactionOperationsItems struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// operation
	// Pattern: ^[^\s]+$
	Operation string `json:"operation,omitempty"`

	// response
	Response string `json:"response,omitempty"`
}

// Validate validates this transaction operations items
func (m *TransactionOperationsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionOperationsItems) validateOperation(formats strfmt.Registry) error {

	if swag.IsZero(m.Operation) { // not required
		return nil
	}

	if err := validate.Pattern("operation", "body", string(m.Operation), `^[^\s]+$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransactionOperationsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionOperationsItems) UnmarshalBinary(b []byte) error {
	var res TransactionOperationsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
