// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TransactionOperationsItems transaction operations items
// swagger:model transactionOperationsItems
type TransactionOperationsItems struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// operation
	Operation string `json:"operation,omitempty"`

	// response
	Response string `json:"response,omitempty"`
}

// Validate validates this transaction operations items
func (m *TransactionOperationsItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionOperationsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionOperationsItems) UnmarshalBinary(b []byte) error {
	var res TransactionOperationsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
